#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"

export PATH="/usr/bin:/usr/local/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${HERE}/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}"

if [ "$EUID" -eq 0 ]; then
    export XDG_RUNTIME_DIR=/run/user/$(logname -i 2>/dev/null || id -u ${SUDO_USER:-root})
fi

# Továbbítjuk az összes argumentumot a Node felé ($@)
exec node "${HERE}/dist/bundle.js" "$@"
